"""
Django settings for Jbook project.

Generated by 'django-admin startproject' using Django 2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'd6!25!46#2pkq!rck-pk*7z6b47=z*cw92l8$6h20v7ag!e7_o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'captcha',
    'mylogin.apps.MyloginConfig',
    'startpage.apps.StartpageConfig',
    'book_comment.apps.Book_commentConfig',
    'comment_cjc.apps.CommentCjcConfig',
    'newcomment.apps.NewcommentConfig',
    'rest_framework',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware', 
    #to do 等待重新配置
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'Jbook.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,"reactapp/login/build"),
            os.path.join(BASE_DIR,"reactapp/signup/build"),
            os.path.join(BASE_DIR,"reactapp/startpage/build"),
            os.path.join(BASE_DIR,"reactapp/book_comment/build"),
            os.path.join(BASE_DIR,"reactapp/comment_cjc/build"),
            os.path.join(BASE_DIR,"reactapp/newcomment/build"),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Jbook.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME':'USERINFO',
        'USER':'22732',
        'PASSWORD':'*********',
        'HOST':'localhost',
        'PORT':'3306',
    },
}
TIME_ZONE = 'Asia/Shanghai'
USE_TZ = False                      #改为使用当前时区(默认为True)

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#CAPTCHA SETTINGS
CAPTCHA_IMAGE_SIZE = (100, 35)
CAPTCHA_NOISE_FUNCTIONS = (
                            'captcha.helpers.noise_null', 
                            'captcha.helpers.noise_arcs',
                            'captcha.helpers.noise_dots',
                           )
CAPTCHA_BACKGROUND_COLOR = '#ffffff'

CAPTCHA_CHALLENGE_FUNCT = 'captcha.helpers.random_char_challenge'
CAPTCHA_LEGNTH = 4
CAPTCHA_TIMEOUT = 2

#EMAIL SETTINGS
# 发送邮箱验证码
EMAIL_HOST = "smtp.qq.com"     # 服务器
EMAIL_PORT = 25                 # 一般情况下都为25
EMAIL_HOST_USER = "XXXXXXXXX@qq.com"     # 账号
EMAIL_HOST_PASSWORD = "XXXXXXXXX"     # （上面保存的授权码）
EMAIL_USE_TLS = False       # 一般都为False
EMAIL_FROM = "XXXXXXXXX@qq.com"      # 邮箱来自
email_title = '邮箱激活'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS= [
    os.path.join(BASE_DIR, "statics"),
    os.path.join(BASE_DIR,"reactapp/login/build/static"),
    os.path.join(BASE_DIR,"reactapp/signup/build/static"),
    os.path.join(BASE_DIR,"reactapp/startpage/build/static"),
    os.path.join(BASE_DIR,"reactapp/book_comment/build/static"),
    os.path.join(BASE_DIR,"reactapp/comment_cjc/build/static"),
    os.path.join(BASE_DIR,"reactapp/newcomment/build/static"),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#配置CSRF头部
CSRF_HEADER_NAME = 'X-CSRFToken'

#设置图片的保存地址
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR
