# Generated by Django 4.2.6 on 2023-10-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auth_User',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('data', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auth_User_captcha',
            fields=[
                ('email', models.CharField(max_length=128, primary_key=True, serialize=False, unique=True)),
                ('captcha', models.CharField(max_length=64)),
                ('time', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
