# Generated by Django 4.2.6 on 2023-10-16 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth_user',
            name='data',
        ),
        migrations.AlterField(
            model_name='auth_user_captcha',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
