# Generated by Django 4.2.6 on 2023-10-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylogin', '0003_alter_auth_user_captcha_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth_user_captcha',
            name='time',
            field=models.DateTimeField(max_length=128),
        ),
    ]
