# Generated by Django 4.2.6 on 2023-10-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, unique=True)),
                ('author', models.CharField(max_length=64)),
                ('publisher', models.CharField(max_length=64)),
                ('price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(default='CSAPP', on_delete=django.db.models.deletion.CASCADE, to='book_comment.book')),
            ],
        ),
    ]
