# Generated by Django 4.2.6 on 2023-10-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_comment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='book',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
