# Generated by Django 4.2.6 on 2023-10-22 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_cjc', '0002_alter_comment_author_alter_comment_bookname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bookname',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='instruction',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='rate',
        ),
    ]
