# Generated by Django 4.2.6 on 2023-10-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newcomment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(null=True)),
                ('book', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('user', models.CharField(max_length=100, null=True)),
                ('comment', models.CharField(max_length=1024, null=True)),
                ('rate', models.FloatField(max_length=5, null=True)),
            ],
        ),
    ]
