# Generated by Django 4.2.6 on 2023-10-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newcomment', '0004_alter_newcomment_book_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newcomment',
            old_name='book_id',
            new_name='book_id1',
        ),
    ]
