# Generated by Django 4.2.6 on 2023-10-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='course',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='books',
            name='publisher',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
