# Generated by Django 4.2.6 on 2023-10-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0002_books_course_alter_books_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='books',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='rating',
            field=models.FloatField(blank=True),
        ),
    ]
