# Generated by Django 4.2.6 on 2023-10-23 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('startpage', '0003_books_price_alter_books_comment_count_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Books',
        ),
    ]
